### ISSUE TITLE
Camel case complaint

### ISSUE THREAD

**Issue by marcelotedeschi** [vdurante/the-tale-of-underscore#1]
![camelcase](https://user-images.githubusercontent.com/5921389/27384908-fe2692fa-5690-11e7-8bfb-a61910f16bf4.png)

**Comment by vdurante** [comment]
Interessante sua observação, mas eu prefiro Kebab Case


![](https://cdn1.thehunt.com/app/public/system/zine_images/1928257/original/32690b0d230cd48cde83fd271676fcd2.jpg)
